export const ROLES = {
    ceo: {
        title: 'CEO',
        fullTitle: 'Chief Executive Officer',
        isCsuite: true,
        description: 'Leads company vision and strategy',
        hireCost: 0,
        dialogues: [
            "Did you see those Q3 projections? We need to pivot. What do you need from me?",
            "I've been on calls all morning. The board wants results, and I intend to deliver.",
            "Let's schedule a town hall. The team needs to hear our new vision.",
            "Innovation doesn't sleep, and neither should our ambition.",
            "I just got off the phone with our biggest investor. Things are looking up!",
            "We need to think bigger. Much bigger. Galaxy-brain bigger.",
        ],
        animPreference: 'pacing',
    },
    cmo: {
        title: 'CMO',
        fullTitle: 'Chief Marketing Officer',
        isCsuite: true,
        description: 'Drives brand and growth strategy',
        hireCost: 0,
        dialogues: [
            "Our brand awareness is up 200%! Did you see the latest campaign metrics?",
            "I'm brainstorming our next viral campaign. Think bold. Think disruptive.",
            "The social media team crushed it this quarter. Pure creative genius!",
            "We need more whiteboards. I've run out of space for ideas.",
            "Color theory isn't just theory - it's a way of life.",
            "Have you seen our competitor's latest ad? We can do ten times better.",
        ],
        animPreference: 'whiteboard',
    },
    coo: {
        title: 'COO',
        fullTitle: 'Chief Operations Officer',
        isCsuite: true,
        description: 'Oversees daily operations and efficiency',
        hireCost: 0,
        dialogues: [
            "I'm optimizing our workflows. Every second counts when you're scaling.",
            "The operations report is looking solid. We're running lean and mean.",
            "I've identified three bottlenecks in our pipeline. Fixing them now.",
            "Spreadsheets don't lie. And right now, they're telling a good story.",
            "Process improvement isn't glamorous, but it's what keeps the lights on.",
            "I just reorganized the supply chain. Efficiency up 15%.",
        ],
        animPreference: 'focused',
    },
    developer: {
        title: 'Developer',
        fullTitle: 'Software Developer',
        isCsuite: false,
        description: 'Writes and maintains code',
        hireCost: 500,
        dialogues: [
            "I'm in the zone right now, trying to fix this memory leak. Can it wait?",
            "Just deployed a new feature. Zero bugs... probably.",
            "Stack overflow saved my life again today.",
            "I've been refactoring this module for three days. It's almost beautiful.",
            "Coffee and code - the two pillars of civilization.",
            "Don't touch my setup. I've got 47 terminal tabs open and I know where each one is.",
        ],
        animPreference: 'typing',
    },
    designer: {
        title: 'Designer',
        fullTitle: 'UI/UX Designer',
        isCsuite: false,
        description: 'Creates user interfaces and experiences',
        hireCost: 500,
        dialogues: [
            "I'm tweaking the kerning on this header. It's off by half a pixel.",
            "User research shows they want less clicks. I'm making it happen.",
            "This color palette speaks to me on a spiritual level.",
            "I just finished the new prototype. Want to see? It's gorgeous.",
            "Whitespace is not empty space. It's breathing room for design.",
            "Comic Sans? Over my dead body.",
        ],
        animPreference: 'typing',
    },
    sales: {
        title: 'Sales Rep',
        fullTitle: 'Sales Representative',
        isCsuite: false,
        description: 'Drives revenue and client relationships',
        hireCost: 400,
        dialogues: [
            "Just closed a huge deal! Time to update the leaderboard.",
            "I've got a call in five. This one's going to be big.",
            "Did someone say quota? Already crushed it this month.",
            "Relationship building isn't a skill - it's an art form.",
            "The pipeline is looking fantastic. Q4 is going to be legendary.",
            "Always be closing. That's my mantra.",
        ],
        animPreference: 'phone',
    },
    hr: {
        title: 'HR Manager',
        fullTitle: 'Human Resources Manager',
        isCsuite: false,
        description: 'Manages people and culture',
        hireCost: 450,
        dialogues: [
            "I'm planning the next team-building event. Escape rooms this time!",
            "Employee satisfaction scores are at an all-time high.",
            "I just finished updating the onboarding documentation.",
            "Culture isn't just a buzzword here - we live it every day.",
            "Conflict resolution is my superpower.",
            "Have you filled out your quarterly self-review yet?",
        ],
        animPreference: 'typing',
    },
    intern: {
        title: 'Intern',
        fullTitle: 'Junior Intern',
        isCsuite: false,
        description: 'Learning the ropes',
        hireCost: 100,
        dialogues: [
            "Uh, hi! I'm just trying to figure out where the coffee filters are stored.",
            "Is it okay if I shadow you today? I'm learning so much!",
            "I made a spreadsheet of all the spreadsheets. Recursive productivity!",
            "This is way different from college. In a good way... I think?",
            "Should I take notes? I feel like I should take notes.",
            "I accidentally sent a test email to the whole company. Sorry about that...",
        ],
        animPreference: 'nervous',
    },
};

export const HIRABLE_ROLES = ['developer', 'designer', 'sales', 'hr', 'intern'];
